In [1]:
import numpy as np
from tqdm import tqdm
from utils import read_data, read_query, read_output, knn, distances, split_normal_distribution, _recall, recall

In [2]:
data_path = '../data/dummy-data.bin'
query_path = '../data/dummy-queries.bin'

output_path_1 = '../data/dummy-output-seqscan.bin'
output_path_2 = '../data/dummy-output-seqscanrange.bin'

In [3]:
# read data, query and output1, output2
data = read_data(data_path)
query = read_query(query_path) 
output1 = read_output(output_path_1, query.shape[0]).astype(int)
output2 = read_output(output_path_2, query.shape[0]).astype(int)
# calculate distances of outputs

print("="*10)
print("data shape", data.shape)
print("query shape", query.shape)
print("="*10)
print("output1 shape", output1.shape)
print("output2 shape", output2.shape)
print("="*4,"KNN","="*4)


# True knn
output_true, dist, dist_true = knn(data, query, 100)
dist_output1 = distances(output1, dist)
#dist_output2 = distances(output2, dist)

print("="*10)
print("output_true shape", output_true.shape)
print("dist shape", dist.shape)
print("="*10)
print("dist_true shape", dist_true.shape)
print("dist_output1 shape", dist_output1.shape)


data shape (10000, 102)
query shape (100, 104)
output1 shape (100, 100)
output2 shape (100, 100)
==== KNN ====


100%|██████████| 100/100 [00:01<00:00, 58.89it/s]

output_true shape (100, 100)
dist shape (10000, 100)
dist_true shape (100, 100)
dist_output1 shape (100, 100)


testing __'_recall'__ : simple recall between two 1D vectors 

In [4]:
a = np.array([5,10,20,30,np.inf])
a_idx = np.array([0,1,2,3,5])

b = np.array([10,20,30,40,40])
b_idx = np.array([1,2,3,4,4])

# replace inf with max value and return the index of the max value
a[a == np.inf] = np.max(a[np.isfinite(a)])
a.argmax()


_recall(a_idx,b_idx,a,b)


3 / 4


0.75

In [5]:
a = np.array([5,10,20,30,40])
a_idx = np.array([0,1,2,3,5])

b = np.array([10,20,30,40,40])
b_idx = np.array([1,2,3,4,4])

# replace inf with max value and return the index of the max value
a[a == np.inf] = np.max(a[np.isfinite(a)])
a.argmax()


_recall(a_idx,b_idx,a,b)

4 / 5


0.8

In [6]:
a = np.array([5,10,20,30,35])
a_idx = np.array([0,1,2,3,5])

b = np.array([5,10,20,30,40])
b_idx = np.array([0,1,2,3,6])

# replace inf with max value and return the index of the max value
a[a == np.inf] = np.max(a[np.isfinite(a)])
a.argmax()


_recall(a_idx,b_idx,a,b)

4 / 5


0.8

testing _recall_

In [7]:
recall(output_true, output1, dist_true, dist_output1)
    

1 / 100
2 / 100
3 / 100
18 / 100
0 / 100
1 / 100
5 / 100
2 / 100
3 / 100
23 / 100
7 / 100
1 / 100
64 / 100
3 / 100
29 / 100
1 / 100
92 / 100
5 / 100
5 / 100
0 / 100
1 / 100
7 / 100
71 / 100
0 / 100
3 / 100
2 / 100
32 / 100
0 / 100
4 / 100
7 / 100
5 / 100
0 / 100
2 / 100
9 / 100
2 / 100
2 / 100
1 / 100
10 / 100
0 / 100
2 / 100
4 / 100
17 / 100
0 / 100
3 / 100
6 / 100
1 / 100
3 / 100
4 / 100
25 / 100
0 / 100
30 / 100
4 / 100
4 / 100
1 / 100
2 / 100
5 / 100
3 / 100
0 / 100
0 / 100
1 / 100
1 / 100
2 / 100
17 / 100
1 / 100
5 / 100
5 / 100
3 / 100
1 / 100
6 / 100
5 / 100
9 / 100
0 / 100
19 / 100
2 / 100
12 / 100
0 / 100
65 / 100
0 / 100
13 / 100
1 / 100
3 / 100
2 / 100
25 / 100
0 / 100
2 / 100
1 / 100
4 / 100
0 / 100
14 / 100
4 / 100
4 / 100
6 / 100
5 / 100
10 / 100
1 / 100
5 / 100
2 / 100
49 / 100
0 / 100
17 / 100


0.08589999999999991

In [8]:
recall(output_true, output_true, dist_true, dist_true)

100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100
100 / 100


1.0

generate breakpoints

In [10]:
split_normal_distribution(2)

Breakpoints for 2 equal parts:
Breakpoint 1: z-score = 0.0000


array([0.])

In [11]:
split_normal_distribution(3)

Breakpoints for 3 equal parts:
Breakpoint 1: z-score = -0.4307
Breakpoint 2: z-score = 0.4307


array([-0.4307273,  0.4307273])

In [12]:
split_normal_distribution(8)

Breakpoints for 8 equal parts:
Breakpoint 1: z-score = -1.1503
Breakpoint 2: z-score = -0.6745
Breakpoint 3: z-score = -0.3186
Breakpoint 4: z-score = 0.0000
Breakpoint 5: z-score = 0.3186
Breakpoint 6: z-score = 0.6745
Breakpoint 7: z-score = 1.1503


array([-1.15034938, -0.67448975, -0.31863936,  0.        ,  0.31863936,
        0.67448975,  1.15034938])

In [13]:
split_normal_distribution(256)

Breakpoints for 256 equal parts:
Breakpoint 1: z-score = -2.6601
Breakpoint 2: z-score = -2.4176
Breakpoint 3: z-score = -2.2662
Breakpoint 4: z-score = -2.1539
Breakpoint 5: z-score = -2.0635
Breakpoint 6: z-score = -1.9874
Breakpoint 7: z-score = -1.9214
Breakpoint 8: z-score = -1.8627
Breakpoint 9: z-score = -1.8099
Breakpoint 10: z-score = -1.7617
Breakpoint 11: z-score = -1.7172
Breakpoint 12: z-score = -1.6759
Breakpoint 13: z-score = -1.6373
Breakpoint 14: z-score = -1.6010
Breakpoint 15: z-score = -1.5667
Breakpoint 16: z-score = -1.5341
Breakpoint 17: z-score = -1.5031
Breakpoint 18: z-score = -1.4735
Breakpoint 19: z-score = -1.4451
Breakpoint 20: z-score = -1.4178
Breakpoint 21: z-score = -1.3915
Breakpoint 22: z-score = -1.3662
Breakpoint 23: z-score = -1.3417
Breakpoint 24: z-score = -1.3180
Breakpoint 25: z-score = -1.2950
Breakpoint 26: z-score = -1.2727
Breakpoint 27: z-score = -1.2510
Breakpoint 28: z-score = -1.2299
Breakpoint 29: z-score = -1.2093
Breakpoint 30: z-sc

array([-2.66006747, -2.41755902, -2.26622681, -2.15387469, -2.0635279 ,
       -1.98742789, -1.92135077, -1.86273187, -1.80989224, -1.76167041,
       -1.71722812, -1.67593972, -1.63732538, -1.60100866, -1.56668859,
       -1.53412054, -1.50310294, -1.47346758, -1.44507258, -1.41779714,
       -1.39153749, -1.36620382, -1.34171784, -1.3180109 , -1.29502241,
       -1.27269864, -1.25099172, -1.22985876, -1.20926123, -1.18916435,
       -1.16953661, -1.15034938, -1.13157656, -1.11319428, -1.09518065,
       -1.07751557, -1.06018048, -1.04315826, -1.02643306, -1.00999017,
       -0.99381591, -0.97789754, -0.9622232 , -0.94678176, -0.93156283,
       -0.91655667, -0.90175411, -0.88714656, -0.87272589, -0.85848447,
       -0.84441508, -0.83051088, -0.81676542, -0.80317257, -0.78972652,
       -0.77642176, -0.76325304, -0.75021538, -0.737304  , -0.72451438,
       -0.7118422 , -0.6992833 , -0.68683375, -0.67448975, -0.66224768,
       -0.65010407, -0.63805558, -0.62609901, -0.61423129, -0.60